theme: jekyll-theme-tactile
title: [Broken links and archiving internet sources exercise]
description: [Exercise as part of the Responsible Research Data Management course at the Erasmus Graduate School for Social Sciences and the Humanities (EGSH). 
During this exercise you will try to relocate internet sources from a list of actual sources used in journal articles.]
